settings:
  permissions:
    ban: "ethos.ban"
    kick: "ethos.kick"
    mute: "ethos.mute"
    unban: "ethos.unban"
    unmute: "ethos.unmute"
    tp: "ethos.tp"
    setpermission: "ethos.setpermission"
    listranks: "ethos.listranks"
    list: "ethos.list"
    info: "ethos.info"
    history: "ethos.history"
    grantrank: "ethos.grantrank"
    gms: "ethos.gms"
    gmc: "ethos.gmc"
    fly: "ethos.fly"
    createrank: "ethos.createrank"
    editrank: "ethos.editrank"
    deleterank: "ethos.deleterank"
