name: Ethos
version: 1.0
main: law.ethos.Ethos
api-version: 1.16

commands:
  createrank:
    description: Creates a new rank
  grantrank:
    description: Grants a rank to a player
  editrank:
    description: Edits an existing rank
  deleterank:
    description: Deletes a rank
  setpermission:
    description: Adds a permission to a rank
  listranks:
    description: Lists all ranks
  list:
    description: Lists all online players with their ranks
  info:
    description: Displays information about a rank or player
  ban:
    description: Bans a player
  kick:
    description: Kicks a player
  mute:
    description: Mutes a player
  unban:
    description: Unbans a player
  unmute:
    description: Unmutes a player
  fly:
    description: Toggles fly mode
  gmc:
    description: Switches to creative mode
  gms:
    description: Switches to survival mode
  tp:
    description: Teleports a player
  history:
    description: Displays punishment history of a player
  ethos.reload:
    description: Allows the player to use /reload.